"""Contextual Retrieval - enriches chunks with document context.

Based on Anthropic's Contextual Retrieval approach:
Each chunk gets a contextual prefix generated by LLM that describes
where it fits in the document, improving embedding quality and retrieval.
"""

from __future__ import annotations
from cortexa.usage.context import usage_action

from dataclasses import dataclass
from typing import List


@dataclass
class ContextualChunk:
    """A chunk enriched with contextual information."""
    original_content: str
    contextual_prefix: str
    enriched_content: str  # prefix + original content
    chunk_index: int
    document_name: str = ""
    metadata: dict | None = None


@usage_action("retrieval_context", source="knowledge")
def generate_contextual_prefix(
    document_content: str,
    chunk_content: str,
    llm=None,
    prompt_template: str | None = None,
) -> str:
    """Generate a contextual prefix for a chunk using LLM.

    Args:
        document_content: The full document content (or a large representative portion).
        chunk_content: The specific chunk to contextualize.
        llm: LLM instance. If None, creates one from config.
        prompt_template: Custom prompt template.

    Returns:
        A short contextual description for the chunk.
    """
    if prompt_template is None:
        prompt_template = (
            "以下是完整的文档内容：\n"
            "<document>\n{doc_content}\n</document>\n\n"
            "以下是需要添加上下文的文档片段：\n"
            "<chunk>\n{chunk_content}\n</chunk>\n\n"
            "请为这个片段生成一句简短的上下文描述，说明：\n"
            "1. 这个片段在文档中的位置（如属于哪个章节/主题）\n"
            "2. 它与文档整体内容的关系\n"
            "只返回上下文描述，不要包含片段本身的内容，不超过100字。"
        )

    # Truncate document if too long (keep first and last portions)
    max_doc_len = 4000
    if len(document_content) > max_doc_len:
        half = max_doc_len // 2
        doc_content = document_content[:half] + "\n...(中间省略)...\n" + document_content[-half:]
    else:
        doc_content = document_content

    if llm is None:
        from cortexa.config.llm_providers import create_llm
        llm = create_llm()

    prompt = prompt_template.format(
        doc_content=doc_content,
        chunk_content=chunk_content[:1000],  # Limit chunk length for prompt
    )

    response = llm.invoke(prompt)
    prefix = response.content if hasattr(response, "content") else str(response)
    return prefix.strip()


def contextualize_chunks(
    document_content: str,
    chunks: List[dict],
    llm=None,
    document_name: str = "",
) -> List[ContextualChunk]:
    """Enrich multiple chunks with contextual prefixes.

    Args:
        document_content: The full document content.
        chunks: List of dicts with at least 'content' and 'index' keys.
        llm: LLM instance.
        document_name: Name of the document for metadata.

    Returns:
        List of ContextualChunk objects with enriched content.
    """
    enriched_chunks = []

    for chunk in chunks:
        chunk_content = chunk.get("content", "")
        chunk_index = chunk.get("index", 0)

        if not chunk_content or len(chunk_content.strip()) < 20:
            # Too short to contextualize
            enriched_chunks.append(ContextualChunk(
                original_content=chunk_content,
                contextual_prefix="",
                enriched_content=chunk_content,
                chunk_index=chunk_index,
                document_name=document_name,
                metadata=chunk.get("metadata"),
            ))
            continue

        try:
            prefix = generate_contextual_prefix(
                document_content, chunk_content, llm
            )
            enriched_content = f"{prefix}\n\n{chunk_content}" if prefix else chunk_content
        except Exception as e:
            print(f"[ContextualRetrieval] Failed to generate context for chunk {chunk_index}: {e}")
            prefix = ""
            enriched_content = chunk_content

        enriched_chunks.append(ContextualChunk(
            original_content=chunk_content,
            contextual_prefix=prefix,
            enriched_content=enriched_content,
            chunk_index=chunk_index,
            document_name=document_name,
            metadata=chunk.get("metadata"),
        ))

    return enriched_chunks


def build_contextual_index(
    document_content: str,
    chunks: List[dict],
    embed_fn=None,
    llm=None,
    document_name: str = "",
) -> List[dict]:
    """Build a contextual index: enrich chunks and compute embeddings.

    Args:
        document_content: Full document text.
        chunks: List of chunk dicts with 'content', 'index', etc.
        embed_fn: Embedding function that takes a list of texts and returns embeddings.
        llm: LLM for context generation.
        document_name: Document name for metadata.

    Returns:
        List of enriched chunk dicts ready for storage, each with
        'content' (enriched), 'embedding', 'contextual_prefix', etc.
    """
    enriched = contextualize_chunks(document_content, chunks, llm, document_name)

    # Generate embeddings for enriched content
    enriched_texts = [c.enriched_content for c in enriched]
    embeddings = []
    if embed_fn and enriched_texts:
        try:
            embeddings = embed_fn(enriched_texts)
        except Exception as e:
            print(f"[ContextualRetrieval] Embedding failed: {e}")
            embeddings = [[] for _ in enriched_texts]

    result = []
    for i, chunk in enumerate(enriched):
        entry = {
            "content": chunk.original_content,  # Store original content
            "enriched_content": chunk.enriched_content,  # For embedding/search
            "contextual_prefix": chunk.contextual_prefix,
            "chunk_index": chunk.chunk_index,
            "document_name": chunk.document_name,
            "metadata": chunk.metadata or {},
        }
        if i < len(embeddings):
            entry["embedding"] = embeddings[i]
        result.append(entry)

    return result
