// Run after npm run build. LIVE_ORIGIN checks deployed assets with isolated API fixtures.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const dist = path.resolve(__dirname, '../../src/agentdevstu/web/static/dist');
const origin = process.env.LIVE_ORIGIN || 'http://knowledge.local';
const folders = [{ id: 'a', name: '产品资料', parent_id: null }, { id: 'b', name: '销售资料', parent_id: null }, { id: 'nested', name: '季度归档', parent_id: 'b' }];
const doc = (id, name, folder_id = null) => ({ id, name, folder_id, status: 'active', created_by: 'user', metadata_json: { size: 1024 } });
const documents = [doc('root', 'Report-root.md'), doc('a1', 'Report-a.pdf', 'a'), doc('b1', 'Report-b.pdf', 'b'), ...Array.from({ length: 12 }, (_, i) => doc('n' + i, '归档-' + i + '.txt', 'nested')), doc('target', 'Report-target.md', 'nested')];
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  try {
    for (const width of [1440, 390]) for (const appearance of ['light', 'dark', 'system']) {
      const page = await browser.newPage({ viewport: { width, height: 1000 }, colorScheme: appearance === 'light' ? 'light' : 'dark' });
      const errors = [];
      page.on('pageerror', error => errors.push(error.message));
      await page.addInitScript(appearance => {
        localStorage.setItem('ui-appearance', appearance);
        localStorage.setItem('ui-appearance:user:user', appearance);
        document.execCommand = command => {
          if (command !== 'copy') return false;
          if (window.failCopy) throw new Error('clipboard unavailable');
          window.copiedPath = document.activeElement.value; return true;
        };
      }, appearance);
      await page.route(origin + '/**', async route => {
        const u = new URL(route.request().url());
        if (u.pathname.startsWith('/api/')) {
          let data = {};
          if (u.pathname === '/api/auth/me') data = { id: 'user', username: 'tester', display_name: '验证账号', system_permissions: ['knowledge.manage', 'knowledge.use'], memberships: [{ workspace_id: 'ws', permissions: ['knowledge.manage', 'knowledge.use'] }] };
          else if (u.pathname === '/api/workspaces') data = [{ id: 'ws', name: '测试工作空间' }];
          else if (u.pathname === '/api/knowledge') data = [{ id: 'kb', name: '知识库验证', status: 'active', document_count: documents.length }];
          else if (u.pathname === '/api/knowledge/kb') data = { id: 'kb', name: '知识库验证', documents, folders };
          else if (u.pathname.endsWith('/folders')) data = folders;
          else if (u.pathname.endsWith('/preview')) data = { name: 'Report-target.md', kind: 'text', status: 'ready', page_count: 1 };
          else if (u.pathname.includes('/pages/')) data = { content: '预览不改变筛选条件' };
          return route.fulfill({ json: data });
        }
        if (process.env.LIVE_ORIGIN) return route.continue();
        const file = u.pathname.startsWith('/static/dist/') ? path.join(dist, u.pathname.slice('/static/dist/'.length)) : path.join(dist, 'index.html');
        if (!fs.existsSync(file)) return route.fulfill({ status: 404, body: '' });
        return route.fulfill({ body: fs.readFileSync(file), contentType: file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html' });
      });
      await page.goto(origin + '/knowledge');
      await page.getByRole('button', { name: '展开', exact: true }).click();
      assert.equal(await page.evaluate(() => document.documentElement.dataset.appearance), appearance);
      const search = page.getByRole('textbox', { name: '搜索文件名称' });
      const rows = page.locator('.document-row');
      const resultCount = async count => {
        await page.waitForFunction(count => document.querySelector('.search-results-heading')?.textContent.includes('找到 ' + count + ' 个文件'), count);
        assert.equal(await page.locator('.folder-tree').count(), 0);
        assert.equal(await page.locator('.folder-row').count(), 0);
      };
      assert.equal(await page.locator('.file-type-filter[aria-pressed=true]').count(), 0);
      assert.equal(await page.locator('.folder-tree').count(), 0);
      assert.equal(await rows.count(), 1);
      assert.equal(await page.locator('.documents-toolbar .explorer-toggle').count(), 0);
      const rail = await page.locator('.explorer-pane').boundingBox();
      const list = await page.locator('.document-list').boundingBox();
      const toolbar = await page.locator('.documents-toolbar').boundingBox();
      assert.ok(rail.width <= 40 && list.x > rail.x + rail.width);
      assert.ok(rail.y >= toolbar.y + toolbar.height);
      await page.screenshot({path: '/tmp/explorer-rail-' + width + '-' + appearance + '.png'});
      await page.getByRole('button', { name: '全部类型', exact: true }).click();
      await resultCount(documents.length);
      assert.equal(await rows.count(), 10);
      await page.getByRole('button', { name: '下一页', exact: true }).click();
      assert.equal(await rows.count(), documents.length - 10);
      await page.getByRole('button', { name: '全部类型', exact: true }).click();
      assert.equal(await page.locator('.search-results-heading').count(), 0);
      assert.equal(await rows.count(), 1);
      await page.getByRole('button', { name: '展开资源管理器', exact: true }).click();
      await page.locator('.tree-root').waitFor();
      const pane = await page.locator('.explorer-pane').boundingBox();
      const expandedList = await page.locator('.document-list').boundingBox();
      assert.ok(pane.width > 100 && expandedList.x >= pane.x + pane.width);
      await page.screenshot({path: '/tmp/explorer-pane-' + width + '-' + appearance + '.png'});
      await page.getByRole('button', { name: '收起资源管理器', exact: true }).click();
      assert.equal(await page.locator('.folder-tree').count(), 0);
      await page.getByRole('button', { name: '展开资源管理器', exact: true }).click();
      await page.locator('.tree-item').filter({ hasText: '产品资料' }).locator('.tree-folder').click();
      const branch = page.locator('.tree-item').filter({ hasText: '销售资料' });
      const child = page.locator('.tree-item').filter({ hasText: '季度归档' });
      await branch.getByRole('button', { name: '展开子文件夹 销售资料', exact: true }).click();
      await child.waitFor();
      assert.ok(await page.locator('[data-document-id=a1]').isVisible());
      await page.locator('.tree-item.selected').filter({ hasText: '产品资料' }).waitFor();
      await branch.getByRole('button', { name: '收起子文件夹 销售资料', exact: true }).focus();
      await page.keyboard.press('Enter');
      assert.equal(await child.count(), 0);
      assert.ok(await page.locator('[data-document-id=a1]').isVisible());
      await branch.locator('.tree-folder').click();
      assert.ok(await page.locator('[data-document-id=b1]').isVisible());
      assert.equal(await child.count(), 0, 'opening a folder must not toggle its children');
      await branch.getByRole('button', { name: '展开子文件夹 销售资料', exact: true }).click();
      await child.locator('.tree-folder').click();
      const beforeCollapse = await rows.allTextContents();
      const breadcrumbs = await page.locator('.header-breadcrumbs').innerText();
      await branch.getByRole('button', { name: '收起子文件夹 销售资料', exact: true }).click();
      assert.equal(await child.count(), 0);
      assert.deepEqual(await rows.allTextContents(), beforeCollapse);
      assert.equal(await page.locator('.header-breadcrumbs').innerText(), breadcrumbs);
      await branch.getByRole('button', { name: '展开子文件夹 销售资料', exact: true }).click();
      await page.locator('.tree-item.selected').filter({ hasText: '季度归档' }).waitFor();
      await page.locator('.tree-item').filter({ hasText: '产品资料' }).locator('.tree-folder').click();
      await page.getByRole('checkbox', { name: '选择 Report-a.pdf', exact: true }).check();
      await search.fill('  rEpOrT  ');
      await resultCount(4);
      assert.equal(await rows.count(), 4);
      assert.equal(await page.locator('.document-row input:checked').count(), 0);
      const target = page.locator('[data-document-id=target]');
      assert.equal(await target.locator('.document-path-text').count(), 0);
      assert.equal(await target.getByRole('button', { name: '复制文件路径 Report-target.md', exact: true }).getAttribute('title'), '复制完整路径：知识库验证 / 销售资料 / 季度归档 / Report-target.md');
      await target.getByRole('button', { name: '复制文件路径 Report-target.md', exact: true }).click();
      assert.equal(await page.evaluate(() => window.copiedPath), '知识库验证 / 销售资料 / 季度归档 / Report-target.md');
      await page.evaluate(() => { window.failCopy = true; });
      await target.getByRole('button', { name: '复制文件路径 Report-target.md', exact: true }).click();
      await page.getByText('复制路径失败，请重试', { exact: true }).waitFor();
      assert.equal(await page.locator('textarea[readonly]').count(), 0);
      await page.evaluate(() => { window.failCopy = false; });
      await target.locator('.preview-action').click();
      await page.locator('.markdown-page').waitFor();
      await page.getByRole('button', { name: '关闭预览', exact: true }).click();
      assert.equal(await search.inputValue(), '  rEpOrT  ');
      await resultCount(4);
      await page.getByText('复制路径失败，请重试', { exact: true }).waitFor({ state: 'hidden' });
      if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: path.join(process.env.SCREENSHOT_DIR, `knowledge-search-${width}-${appearance}.png`), fullPage: true });
      if (appearance === 'system') {
        await page.emulateMedia({ colorScheme: 'light' });
        await page.waitForFunction(() => document.documentElement.dataset.theme === 'light');
        await resultCount(4);
      }
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'page must not overflow horizontally');
      await page.getByRole('button', { name: 'PDF', exact: true }).click();
      await resultCount(2);
      await search.fill('');
      await resultCount(2);
      await search.fill('不存在');
      await resultCount(0);
      await page.getByText('整个知识库中没有匹配的文件', { exact: true }).waitFor();
      await page.getByRole('button', { name: '返回文件夹浏览', exact: true }).click();
      await page.locator('.tree-item.selected').filter({ hasText: '产品资料' }).waitFor();
      assert.equal(await rows.count(), 1);
      assert.equal(await rows.getByRole('button', { name: /^打开所在文件夹 / }).count(), 0);
      assert.equal(await rows.locator('.document-details .copy-path').count(), 1);
      assert.equal(await page.locator('.file-type-filter[aria-pressed=true]').count(), 0);
      await search.fill('Report-target');
      await resultCount(1);
      await target.getByRole('button', { name: '打开所在文件夹 Report-target.md', exact: true }).click();
      await page.locator('.document-row.located[data-document-id=target]').waitFor();
      assert.equal(await search.inputValue(), '');
      assert.ok((await page.locator('.list-pagination').innerText()).includes('2 / 2'));
      await page.locator('.tree-item.selected').filter({ hasText: '季度归档' }).waitFor();
      assert.equal(await target.evaluate(element => document.activeElement === element), true);
      await search.fill('归档');
      await resultCount(12);
      await page.getByRole('checkbox', { name: '选择 归档-0.txt', exact: true }).check();
      await page.getByRole('checkbox', { name: '本页全选', exact: true }).check();
      assert.equal(await page.locator('.document-row input:checked').count(), 10);
      await page.getByRole('button', { name: '下一页', exact: true }).click();
      assert.equal(await rows.count(), 2);
      await search.fill('Report-root');
      await resultCount(1);
      assert.equal(await page.locator('.document-row input:checked').count(), 0);
      await page.getByRole('button', { name: '打开所在文件夹 Report-root.md', exact: true }).click();
      await page.locator('.tree-root.selected').waitFor();
      await page.locator('.document-row.located[data-document-id=root]').waitFor();
      await search.fill('   ');
      assert.equal(await page.locator('.folder-tree').count(), 1);
      assert.deepEqual(errors, []);
      console.log('PASS', width, appearance, 'global/combined/empty search, copy, preview, restore, pagination, selection, locate');
      await page.close();
    }
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
