const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs'), path = require('path'), assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({headless:true,channel:'chrome'});
 try {
 const page = await browser.newPage({viewport:{width:1440,height:1050}});
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 const root=path.resolve(__dirname,'../../src/cortexa/web/static/dist');
 let user='alice';
 await page.route('http://theme.local/**', async r=>{
  const u=new URL(r.request().url());
  if(u.pathname.startsWith('/api/')) {
   let data=[];
   if(u.pathname==='/api/auth/me') data={id:user,display_name:user,username:user,system_permissions:[],memberships:[{workspace_id:'w',permissions:[]}]};
   if(u.pathname==='/api/workspaces') data=[{id:'w',name:'测试空间'}];
   return r.fulfill({json:data});
  }
  const file=u.pathname.startsWith('/static/dist/')?path.join(root,u.pathname.slice(13)):path.join(root,'index.html');
  return r.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html'});
 });
 await page.goto('http://theme.local/works');
 await page.getByRole('button',{name:'账号菜单'}).click();
 await page.getByRole('link',{name:'个性化设置'}).click();
 await page.locator('.theme-group-tab').first().waitFor();
 assert.equal(await page.getByRole('link',{name:'系统配置',exact:true}).count(),0);
 assert.deepEqual(await page.locator('.theme-group-tab').allTextContents(),['纯色 98','撞色 14','渐变 14','玻璃 14','纹理 25']);
 await page.getByRole('tab',{name:'纯色 98',exact:true}).click();
 assert.deepEqual(await page.locator('.solid-categories button').allTextContents(),['经典','科技','马卡龙','莫兰迪','糖果宝石','东方美学','欧式宫廷']);
 for (const category of ['经典','科技','马卡龙','莫兰迪','糖果宝石','东方美学','欧式宫廷']) {
   await page.locator('.solid-categories').getByRole('button',{name:category,exact:true}).click();
   assert.equal(await page.locator('.theme-color-item').count(),15); // 14 presets plus custom color
 }
 await page.locator('.solid-categories').getByRole('button',{name:'马卡龙',exact:true}).click();
 await page.getByRole('button',{name:'草莓奶昔',exact:false}).click();
 await page.reload();
 await page.locator('.theme-group-tab').first().waitFor();
 assert.equal(await page.locator('.solid-categories button[aria-pressed=true]').textContent(),'马卡龙');
 assert.equal(await page.locator('.theme-color-item.active .color-name').textContent(),'草莓奶昔');
await page.getByRole('tab',{name:'玻璃 14',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'液态',exact:true}).getAttribute('aria-pressed'),'true');
await page.getByRole('button',{name:'冰川蓝',exact:false}).click();
 let glassSaved=await page.evaluate(()=>JSON.parse(localStorage.getItem('theme-color:user:alice')));
 assert.deepEqual(glassSaved,{value:'#009EFF',mode:'glass',finish:'clear'});
 assert.match(await page.locator('.theme-color-item.active .color-preview').evaluate(e=>getComputedStyle(e).backgroundImage),/radial-gradient/);
 assert.match(await page.locator('.theme-demo-button').evaluate(e=>getComputedStyle(e).backgroundImage),/radial-gradient/);
 assert.match(await page.locator('.theme-demo-button').evaluate(e=>getComputedStyle(e).backdropFilter),/blur\(14px\)/);
 const demoButton=page.locator('.theme-demo-button');
 const box=await demoButton.boundingBox();
 await page.mouse.move(box.x + 8, box.y + 8);
 await page.waitForTimeout(40);
 const firstImage=await demoButton.evaluate(e=>getComputedStyle(e).backgroundImage);
 await page.mouse.move(box.x + box.width - 8, box.y + box.height - 8);
 await page.waitForTimeout(40);
 const secondImage=await demoButton.evaluate(e=>getComputedStyle(e).backgroundImage);
 assert.notEqual(firstImage,secondImage);
 await page.evaluate(()=>{
   const fixture=document.createElement('div'); fixture.id='lighting-fixture';
   fixture.style.cssText='position:fixed;left:300px;top:200px;z-index:9999;display:flex;gap:40px';
   fixture.innerHTML='<button class="btn btn-primary" style="width:100px;height:40px">Left</button><button class="btn btn-primary" style="width:100px;height:40px">Right</button><button class="btn btn-primary" style="margin-left:300px;width:100px;height:40px">Far</button>';
   document.body.append(fixture);
 });
 await page.mouse.move(420,220);
 await page.waitForTimeout(60);
 const lights=await page.locator('#lighting-fixture button').evaluateAll(es=>es.map(e=>({inline:e.style.backgroundImage,rendered:getComputedStyle(e).backgroundImage})));
 assert.match(lights[0].inline,/radial-gradient/);
 assert.match(lights[1].inline,/radial-gradient/);
 assert.equal(lights[2].inline,'');
 assert.notEqual(lights[0].rendered,lights[1].rendered);
 await page.mouse.move(0,0);
 await page.waitForTimeout(60);
 assert.equal(await page.locator('#lighting-fixture button').first().evaluate(e=>e.style.backgroundImage),'');
 await page.locator('#lighting-fixture').evaluate(e=>e.remove());
 await page.mouse.move(0,0);
 assert.deepEqual(await page.evaluate(()=>[document.documentElement.style.getPropertyValue('--glass-x'),document.documentElement.style.getPropertyValue('--glass-y')]),['','']);
 await page.getByRole('button',{name:'浅色',exact:true}).click();
 await page.waitForTimeout(250);
 await page.screenshot({path:'/tmp/glass-clear-light.png',fullPage:true});
 await page.getByRole('button',{name:'磨砂',exact:true}).click();
 assert.match(await page.locator('.theme-demo-button').evaluate(e=>getComputedStyle(e).backdropFilter),/blur\(28px\)/);
 assert.match(await page.locator('.theme-demo-button').evaluate(e=>getComputedStyle(e).backgroundImage),/data:image\/svg\+xml/);
 await page.getByRole('button',{name:'自定义玻璃',exact:false}).click();
 await page.getByLabel('自定义玻璃颜色').fill('#315A7D');
 glassSaved=await page.evaluate(()=>JSON.parse(localStorage.getItem('theme-color:user:alice')));
 assert.deepEqual(glassSaved,{value:'#315A7D',mode:'glass',finish:'frosted'});
 const beforeGlow=await demoButton.evaluate(e=>getComputedStyle(e).backgroundImage);
 await page.getByRole('slider',{name:'边缘泛光强度'}).fill('85');
 await page.mouse.move(0,0);
 await page.waitForTimeout(60);
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('theme-color:user:alice')).glow),85);
 assert.notEqual(await demoButton.evaluate(e=>getComputedStyle(e).backgroundImage),beforeGlow);
 await page.reload();
 await page.locator('.theme-group-tab').first().waitFor();
 assert.equal(await page.getByRole('slider',{name:'边缘泛光强度'}).inputValue(),'85');
 await page.getByRole('button',{name:'液态',exact:true}).click();
 assert.equal(await page.getByRole('slider',{name:'边缘泛光强度'}).inputValue(),'85');
 await page.getByRole('button',{name:'磨砂',exact:true}).click();
 await page.getByRole('button',{name:'浅色',exact:true}).click();
 await page.waitForTimeout(250);
 assert.equal(await page.locator('.theme-demo-button').evaluate(e=>getComputedStyle(e).color),'rgb(23, 33, 43)');
 await page.screenshot({path:'/tmp/glass-light.png',fullPage:true});
 await page.getByRole('button',{name:'深色',exact:true}).click();
 await page.waitForTimeout(250);
 assert.equal(await page.locator('.theme-demo-button').evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');
 await page.screenshot({path:'/tmp/glass-dark.png',fullPage:true});
 await page.getByRole('link',{name:'工作',exact:true}).click();
 const glassCreate=page.getByRole('button',{name:'＋ 新建工作',exact:true});
 assert.match(await glassCreate.evaluate(e=>getComputedStyle(e).backgroundImage),/radial-gradient/);
 assert.match(await glassCreate.evaluate(e=>getComputedStyle(e).backdropFilter),/blur/);
 assert.match(await page.getByRole('link',{name:'工作',exact:true}).evaluate(e=>getComputedStyle(e).backgroundImage),/radial-gradient/);
 await page.goto('http://theme.local/personalization');
 await page.locator('.theme-group-tab').first().waitFor();
 await page.getByRole('tab',{name:'纹理 25',exact:true}).click();
 for (const category of ['自然','金属','布艺','人文','历史','书艺','绘艺']) {
   await page.locator('.texture-categories').getByRole('button',{name:category,exact:true}).click();
   const expected = ['书艺','绘艺'].includes(category) ? 6 : 4;
   assert.equal(await page.locator('.theme-color-item').count(),expected);
 }
 await page.locator('.texture-categories').getByRole('button',{name:'全部',exact:true}).click();
 assert.equal(await page.locator('.theme-color-item').count(),26);
 await page.getByRole('button',{name:'林间木纹',exact:false}).click();
 let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('theme-color:user:alice')));
 assert.equal(saved.mode,'texture'); assert.equal(saved.texture,'wood');
 assert.match(await page.locator('.theme-color-item.active .color-preview').evaluate(e=>getComputedStyle(e).backgroundImage), /data:image/);
 assert.match(await page.locator('.theme-demo-button').evaluate(e=>getComputedStyle(e).backgroundImage),/data:image/);
 await page.getByRole('link',{name:'工作',exact:true}).click();
 const create = page.getByRole('button',{name:'＋ 新建工作',exact:true});
 assert.match(await create.evaluate(e=>getComputedStyle(e).backgroundImage),/data:image/);
 assert.ok(await create.evaluate(e=>{const probe=document.createElement('span');probe.style.color='var(--theme-button-background)';document.body.append(probe);const expected=getComputedStyle(probe).color;probe.remove();return getComputedStyle(e).backgroundColor===expected}));
 await create.hover();
 assert.match(await create.evaluate(e=>getComputedStyle(e).backgroundImage),/data:image/);
 await page.goto('http://theme.local/personalization');
 await page.locator('.theme-group-tab').first().waitFor();

 await page.getByRole('button',{name:'自定义纹理',exact:false}).click();
 await page.getByLabel('纹理主色').fill('#123456');
 await page.getByRole('button',{name:'纹理样式'}).click();
 await page.getByRole('option',{name:'亚麻经纬'}).click();
 await page.getByRole('button',{name:'浅色',exact:true}).click();
 await page.screenshot({path:'/tmp/texture-light.png',fullPage:true});
 await page.getByRole('button',{name:'深色',exact:true}).click();
 await page.reload();
 await page.locator('.theme-group-tab').first().waitFor();
 assert.equal(await page.locator('.theme-color-item.active .color-name').textContent(),'自定义纹理');
 assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');
 await page.screenshot({path:'/tmp/personalization-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'/tmp/personalization-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1050});
 await page.getByRole('tab',{name:'渐变 14',exact:true}).click();
 await page.getByRole('button',{name:'极光蓝紫',exact:false}).click();
 await page.getByRole('link',{name:'工作',exact:true}).click();
 assert.match(await page.getByRole('button',{name:'＋ 新建工作',exact:true}).evaluate(e=>getComputedStyle(e).backgroundImage),/linear-gradient/);
 user='bob'; await page.goto('http://theme.local/personalization');
 await page.locator('.theme-group-tab').first().waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.style.getPropertyValue('--theme-gradient')),'none');
 assert.equal(await page.evaluate(()=>document.documentElement.dataset.appearance),'system');
 await page.getByRole('tab',{name:'撞色 14',exact:true}).click();
 await page.getByRole('button',{name:'蓝橙交响',exact:false}).click();
 user='alice'; await page.reload();
 await page.locator('.theme-group-tab').first().waitFor();
 assert.equal(await page.locator('.theme-color-item.active .color-name').textContent(),'极光蓝紫');
 assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');
 await page.evaluate(()=>localStorage.setItem('theme-color:user:alice',JSON.stringify({value:'#52684B',accent:'#F97316',tertiary:'#14B8A6',mode:'tricolor'})));
 await page.reload();
 await page.locator('.theme-group-tab').first().waitFor();
 assert.equal(await page.getByRole('tab',{name:'纹理 25',exact:true}).getAttribute('aria-selected'),'true');
 assert.equal(await page.locator('.theme-color-item.active .color-name').textContent(),'林间木纹');
 assert.match(await page.locator('.theme-demo-button').evaluate(e=>getComputedStyle(e).backgroundImage),/data:image/);
 assert.deepEqual(errors,[]);
 console.log('PASS: ordinary-user access, texture categories/custom save, reload, account isolation, appearance, gradient work button, mobile layout');
 } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1)});
